"""Planner agent — analytical task decomposition.

Decomposes complex, multi-part analytical queries into an ordered sequence
of executable Subtask items. Leverages Pydantic structured output with Gemini.
"""

from typing import List, Literal, Optional
from langchain_core.messages import AIMessage, SystemMessage
from langgraph.types import Command
from pydantic import BaseModel, Field

from backend.app.config import get_llm
from backend.app.graph.state import Subtask

PLANNER_SYSTEM_PROMPT = """\
You are an expert Chief Data Scientist and Analytical Planner.
Your job is to analyze user requests about a tabular dataset and decompose them into an optimal, ordered plan of discrete subtasks.

## Guidelines:
1. Examine the user's question and the dataset schema/profile.
2. If the question is simple/direct (e.g., "What is the average age?", "How many rows?"):
   - Set is_complex = False.
   - Create exactly 1 concise subtask.
3. If the question is multi-step (e.g., "Find top 3 categories by sales, calculate their profit margins, and plot a chart", "Compare survival rates across age groups and passenger classes"):
   - Set is_complex = True.
   - Break down into 2 to 4 sequential, self-contained subtasks.
   - Make each subtask description clear and actionable for a Python/pandas coder.
   - If visualization is requested, make the final subtask specifically describe the chart to generate.

## Dataset Profile:
{profile_summary}
"""


class PlanOutput(BaseModel):
    """Structured plan output generated by the Planner agent."""

    reasoning: str = Field(description="Brief explanation of the analytical approach")
    is_complex: bool = Field(description="True if query requires multiple subtasks, False if single direct step")
    subtasks: List[Subtask] = Field(description="Ordered list of executable subtasks")


def planner_node(state: dict) -> Command:
    """LangGraph node: Planner agent decomposes the user's prompt into an executable plan."""
    messages = state.get("messages", [])
    if not messages:
        return Command(
            update={"messages": [AIMessage(content="Please provide an analytical question about the dataset.")]},
            goto="coder"
        )

    user_query = messages[-1].content if hasattr(messages[-1], "content") else str(messages[-1])

    # Extract schema / profile summary
    profile = state.get("dataset_profile")
    profile_summary = profile.get("summary_text") if profile else "No profile summary available."

    system_msg = SystemMessage(content=PLANNER_SYSTEM_PROMPT.format(profile_summary=profile_summary))

    try:
        llm = get_llm("flash")
        structured_llm = llm.with_structured_output(PlanOutput)
        plan_result: PlanOutput = structured_llm.invoke([system_msg] + list(messages))

        # Ensure subtasks have proper default status and sequential IDs
        formatted_subtasks = []
        for i, st in enumerate(plan_result.subtasks, 1):
            subtask = Subtask(
                id=f"task_{i}",
                description=st.description,
                status="pending",
                result=None,
                retries=0,
            )
            formatted_subtasks.append(subtask)

        if not formatted_subtasks:
            formatted_subtasks = [
                Subtask(id="task_1", description=user_query, status="pending")
            ]

        return {
            "plan": formatted_subtasks,
            "current_subtask_idx": 0,
        }

    except Exception as e:
        fallback_subtask = [
            Subtask(id="task_1", description=user_query, status="pending")
        ]
        return {
            "plan": fallback_subtask,
            "current_subtask_idx": 0,
        }
